server:
  port: 8080

spring:
  config:
    activate:
      on-profile: default

  datasource:
    url: jdbc:mysql://localhost:3306/Moneytrack
    username: root
    password: ma582468
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update

  mail:
    host: localhost
    port: 465
    username: root
    password: ma582468
