spring:
  profiles:
    active: @spring.profiles.active@

  datasource:
    url: jdbc:mysql://localhost:3306/Moneytrack
    username: root
    password: ma582468
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

  mail:
    host: localhost
    port: 1025
    username: root
    password: ma582468
