spring:
  datasource:
    url: jdbc:mysql://moneytrack-database-test.cibdc9rthbdi.eu-central-1.rds.amazonaws.com:3306/Moneytrack
    username: root
    password: ma582468
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update

  mail:
    host: localhost
    port: 1025
    username: root
    password: ma582468